name: hello-github-actions

# 触发 workflow 的事件
on: 
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    
jobs:
  growth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node 
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      
      - name: Depend install and serve
        env: 
          TOKEN: ${{ secret.TOKEN }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: |
          npm install
          npm run serve